import type { Metadata } from "next";
import { Geist, Geist_Mono, Plus_Jakarta_Sans, Comfortaa  } from "next/font/google";
import "./globals.css";
import { TooltipProvider } from "@/components/ui/tooltip"
import { getCurrentUser } from "@/lib/user";
import { Providers } from "./providers";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const jakarta = Plus_Jakarta_Sans({
  variable: "--font-jakarta",
  subsets: ["latin"],
  weight: ["600", "700", "800"],
})

const comfortaa = Comfortaa({
  variable: "--font-comfortaa",
  subsets: ["latin"],
  weight: ["500", "600", "700"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: LayoutProps<"/">) {

  const user = await getCurrentUser()
  console.log("current user in RootLayout:", user)

  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${jakarta.variable} ${comfortaa.variable} h-full antialiased`}
    >
        <Providers user={user}>
          <TooltipProvider>
            <body className="min-h-full flex flex-col">
                {children}
            </body>
          </TooltipProvider>
        </Providers>
    </html>
  );
}
